name: CD Pipeline

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types: 
     - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      if: contains(github.ref, 'main')
      with:
        host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }} #.pem private key
        envs: GITHUB_SHA
        script: |
          sudo docker pull haileythegooner/world-whalealert:latest
          sudo docker rm -f world-whalealert-container || true 
          sudo docker image prune -f
          
          echo "DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}}" >> .env.ai.production
          echo "DISCORD_URL=${{secrets.DISCORD_URL}}" >> .env.ai.production
          echo "DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}" >> .env.ai.production
          echo "DISCORD_CHANNELID=${{secrets.DISCORD_CHANNELID}}" >> .env.ai.production


          echo "APP_KEY=${{secrets.APP_KEY}}" >> .env.ai.production
          echo "APP_SECRET=${{secrets.APP_SECRET}}" >> .env.ai.production
          echo "BEARER_TOKEN=${{secrets.BEARER_TOKEN}}" >> .env.ai.production
          echo "ACCESS_TOKEN=${{secrets.ACCESS_TOKEN}}" >> .env.ai.production
          echo "ACCESS_SECRET=${{secrets.ACCESS_SECRET}}" >> .env.ai.production
          echo "CLIENT_ID=${{secrets.CLIENT_ID}}"  >> .env.ai.production 
          echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}"  >> .env.ai.production
          
          echo "TELEGRAM_TOKEN=${{secrets.TELEGRAM_TOKEN}}" >> .env.ai.production
          echo "NGROK_SEVER_URL=${{secrets.NGROK_SEVER_URL}}" >> .env.ai.production
      
          echo "WSETHURL=${{secrets.WSETHURL}}" >> .env.ai.production
         
         
          sudo docker run --env-file ./.env.ai.production -d -p 8080:8080 --name world-whalealert-container haileythegooner/world-whalealert

      
      





     
      
